name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/static/index.html'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set short SHA
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Check outputs
        run: echo ${{ env.sha_short }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            tamilarasug/todoapp:latest
            tamilarasug/todoapp:${{ env.sha_short }}
